before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - go_118_first_class
    binary: cuegen
    ldflags:
      - "-s -w -X github.com/noris-network/cuegen/internal/app.build={{.Version}}"
    flags:
      - "-trimpath"
    mod_timestamp: "{{ .CommitTimestamp }}"
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
