apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: cuegen
spec:
  version: VERSION
  generate:
    command: ["/bin/cuegen", "."]
  discover:
    find:
      command: ["/bin/cuegen", "-is-cuegen-dir"]
