name: release

on:
  push:
    tags:
      - "v*"

jobs:
  publishGitRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.20.0"
          check-latest: true

      - name: Get Version
        id: get_version
        run: echo "VERSION=${GITHUB_REF##*/}" >> "${GITHUB_OUTPUT}"

      - name: Run Tests
        run: go test ./tests ./internal/cuegen

      - name: Test Examples
        run: |
          go build -o cuegen .
          export PATH=$PWD:$PATH
          ./scripts/test-all-examples.sh
          rm cuegen

      - name: Run Goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --config=.goreleaser.yaml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.get_version.outputs.VERSION }}
