name: release

on:
  push:

jobs:
  publishGitRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.20.0"
          check-latest: true

      - name: Run Tests
        run: go test ./tests

      - name: Run Tests on Examples
        run: |
          go build -o cuegen .
          export PATH=$PWD:$PATH
          ./scripts/test-all-examples.sh
